name: Publish JD
on: ["pull_request", "push"]

env:
  DEST_DIR: _out

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    outputs:
      publishing: "${{ steps.setup.outputs.publishing_branch }}"
    steps:
      - name: "setup"
        id: "setup"
        uses: "KyoriPowered/ci-cookbook/actions/setup-python-env@2025.10.17"
        with:
          working_dir: "_generator/"
      - name: "install dependencies"
        run: |
          poetry -P _generator/ install
      - name: "generate site"
        working-directory: "_generator"
        run: |
          poetry run generate-jd ../$DEST_DIR --metadata ../metadata.yaml --jd-root ..
      - name: "publish"
        if: "${{ github.event_name == 'push' && steps.setup.outputs.publishing_branch != '' }}"
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "${{ env.DEST_DIR }}"
  deploy:
    if: "${{ github.event_name == 'push' && needs.build.outputs.publishing != ''}}"
    needs: "build"
    runs-on: "ubuntu-latest"

    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      - name: "Deploy to GitHub pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
