name: Publish JD
on: ["pull_request", "push"]

env:
  DEST_DIR: _out
  PYTHON_VERSION: "3.10"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v3"
      - name: "setup python ${{ env.PYTHON_VERSION }}"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
      - name: "install dependencies"
        run: |
          pip install poetry
          pushd _generator
          poetry install
      - name: "generate site"
        run: |
          pushd _generator
          poetry run generate-jd ../$DEST_DIR --metadata ../metadata.yaml --jd-root ..
      - name: "publish"
        if: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
        uses: "actions/upload-pages-artifact@v1"
        with:
          path: "${{ env.DEST_DIR }}"
  deploy:
    if: "${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}"
    needs: "build"
    runs-on: "ubuntu-latest"

    permissions:
      pages: "write"
      id-token: "write"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.output.page_url }}"

    steps:
      - name: "Deploy to GitHub pages"
        id: "deployment"
        uses: "actions/deploy-pages@v1"
